import type { MenuItem, TableNode } from "./types";

export const TABLES: TableNode[] = [
  {
    id: "T01",
    name: "Table 01",
    seats: 2,
    top: "8%",
    left: "8%",
    width: "7.5rem",
    height: "7.5rem",
    status: "Occupied",
    shape: "round",
  },
  {
    id: "T02",
    name: "Table 02",
    seats: 4,
    top: "11%",
    left: "32%",
    width: "8.5rem",
    height: "5.75rem",
    status: "Available",
    shape: "rounded",
  },
  {
    id: "T03",
    name: "Table 03",
    seats: 2,
    top: "8%",
    left: "63%",
    width: "7.25rem",
    height: "7.25rem",
    status: "Billing",
    shape: "round",
  },
  {
    id: "T04",
    name: "Table 04",
    seats: 6,
    top: "34%",
    left: "10%",
    width: "9.75rem",
    height: "5.75rem",
    status: "Available",
    shape: "rounded",
  },
  {
    id: "T05",
    name: "Table 05",
    seats: 4,
    top: "38%",
    left: "36%",
    width: "8.25rem",
    height: "8.25rem",
    status: "Occupied",
    shape: "round",
  },
  {
    id: "T06",
    name: "Table 06",
    seats: 2,
    top: "37%",
    left: "67%",
    width: "7rem",
    height: "4.75rem",
    status: "Available",
    shape: "rounded",
  },
  {
    id: "T07",
    name: "Table 07",
    seats: 8,
    top: "67%",
    left: "14%",
    width: "10.5rem",
    height: "5.75rem",
    status: "Available",
    shape: "rounded",
  },
  {
    id: "T08",
    name: "Table 08",
    seats: 2,
    top: "68%",
    left: "49%",
    width: "7.5rem",
    height: "7.5rem",
    status: "Occupied",
    shape: "round",
  },
  {
    id: "T09",
    name: "Table 09",
    seats: 4,
    top: "68%",
    left: "73%",
    width: "8.25rem",
    height: "5.75rem",
    status: "Available",
    shape: "rounded",
  },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "m1",
    name: "Smoked Paneer Tikka",
    description: "Charred skewers with mint chutney and pickled onion.",
    price: 280,
    category: "Starters",
    badge: "Chef Pick",
  },
  {
    id: "m2",
    name: "Truffle Mushroom Pizza",
    description: "Thin crust, mozzarella melt, parmesan dust.",
    price: 420,
    category: "Mains",
    badge: "Popular",
  },
  {
    id: "m3",
    name: "Herb Chicken Skillet",
    description: "Pepper pan sauce with seared vegetables.",
    price: 390,
    category: "Mains",
    badge: "Spicy",
  },
  {
    id: "m4",
    name: "Loaded Nacho Bowl",
    description: "Corn chips, salsa, cream, jalapeno, and salsa verde.",
    price: 260,
    category: "Snacks",
    badge: "Best Seller",
  },
  {
    id: "m5",
    name: "Citrus Cooler",
    description: "Fresh lime, mint, and soda served over pebble ice.",
    price: 140,
    category: "Drinks",
    badge: "Fresh",
  },
  {
    id: "m6",
    name: "Signature Lemon Tea",
    description: "Warm spiced tea with house-made citrus syrup.",
    price: 110,
    category: "Drinks",
    badge: "Hot",
  },
  {
    id: "m7",
    name: "Butter Garlic Prawns",
    description: "Pan finished prawns with herb butter and garlic chips.",
    price: 510,
    category: "Seafood",
    badge: "Premium",
  },
  {
    id: "m8",
    name: "Molten Chocolate Dome",
    description: "Warm center dessert with vanilla bean gelato.",
    price: 240,
    category: "Dessert",
    badge: "Sweet",
  },
  {
    id: "m9",
    name: "Smash Burger Box",
    description: "Double patty burger with fries and aioli dip.",
    price: 360,
    category: "Mains",
    badge: "Combo",
  },
  {
    id: "m10",
    name: "Basil Pesto Pasta",
    description: "Silky pesto, cherry tomato, and grilled zucchini.",
    price: 330,
    category: "Mains",
    badge: "Green",
  },
];